### PR TITLE
correct-ci-failure-multiple-test-runs

### PR DESCRIPTION
**Pull request by JoaoFula**
Adding scaling of operator manager pod and deletion of route

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
it looks ok

**Comment by tisnik** [comment]
/override "Red Hat Konflux / lightspeed-service-on-pull-request"

**Comment by xrajesh** [comment]
/override "Red Hat Konflux / lightspeed-service-on-pull-request"

**Review by tisnik — COMMENTED** [review]
looks good

**Pull request merged**
