### PR TITLE
Print e2e tests durations

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Print e2e tests durations

### CODE REVIEW

**Comment by bparees** [comment]
where will these values be visible?  prow is already showing the test durations:

image

**Comment by tisnik** [comment]
it should sort tests according to durations + print slowest ones at beginning. It's just test if it's useful or not (looking at BAM-slownes)

**Comment by onmete** [comment]
It doesn't really change what is displayed in the CI UI. You can find the test duration in the `build-log.txt` if needed.

/lgtm

**Pull request merged**
