### PR TITLE
upgrade ecosystem-cert-preflight-checks due fixing EC issues

### PR DESCRIPTION
**Pull request by raptorsun**
## Description

Enterprise contract test shows a violation of 

```
The Enterprise Contract test failed due to the issue Pipeline task 'ecosystem-cert-preflight-checks' uses an untrusted task bundle 'quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks: 0.1@sha256:d56dc78e0699771ef6960eef1618b8068bd1b32557a8eed118453b0316772d7d' .
```

The suggested solution is to check if the Tekton Bundle used is a trusted task image. 

The trusted image now is 
```json
{
  "key": "oci://quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.1",
  "value": [
    {
      "effective_on": "2024-07-06T00:00:00Z",
      "ref": "sha256:8838d3e1628dbe61f4851b3640d2e3a9a3079d3ff3da955f4a3e4c2c95a013df"
    }
  ]
}
```

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)

## Related Tickets & Documents

- Related Issue # [OLS-822](https://github.com/openshift/lightspeed-service/compare/main...raptorsun:lightspeed-service:ec_fix_untrusted_task_image?expand=1)
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
looks ok, let's wait for CI

**Comment by raptorsun** [comment]
We can merge now 😜

**Pull request closed without merging**
