### PR TITLE
OLS-186: Unit tests for `RedisCache`

### PR DESCRIPTION
**Pull request by tisnik**
## Description

- Unit tests for `RedisCache`
- Interface for Redis storage is mocked, of course

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [x] Unit tests

## Related Tickets & Documents

- Related Issue #[OLS-186](https://issues.redhat.com//browse/OLS-186)

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- `make test-unit` as usual should display 100% code coverage for `RedisCache`

### CODE REVIEW

**Comment by onmete** [comment]
Is it mock or fake?:P

**Comment by tisnik** [comment]
> Is it mock or fake?:P

it's class with logic. Fakes are usually just encapsulated static data.

**Comment by onmete** [comment]
I thought the difference is that fake is working re-implementations, while mock is using the actual object and just overrides/mocks relevant functionality (like setting `self.redis_client = {}` more or less).

But that might be a topic for some different time, so /lgtm

Btw it's dumb that you can't create a thread on standard comments here (just on review comments).

**Pull request merged**
