### PR TITLE
Explicit return from `try` block

### PR DESCRIPTION
**Pull request by tisnik**
## Description

The `try`-`except` statement has an `else` clause for code that should
run _only_ if no exceptions were raised. Using the `else` clause is more
explicit than using a `return` statement inside of a `try` block.

## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by onmete** [comment]
I can't decide if it is better or worse in terms of code readability. I'll let others to lgtm this one.

**Comment by bparees** [comment]
currently the expected flow of the code would be:

1) do some work
2) return some value
3) if an exception happened in (1), handle it.  This should be unusual.

changing it to:

1) do some work
2) check if an exception happened + handle it
3) return some value from (1)

imho makes it less readable because the return statement is separated from the main logic that setup/computed the return value.  For someone who's reading the code to understand the happy path, they need to recognize that they need to go look at the "else" statement to see what additional steps are going to be executed.

personally when i'm trying to understand code i usually stop reading when i get to the exception handling portion (assuming i don't have a reason to care about it).

all in all it's a bikeshed, but i'm a -1 on this structure.

**Comment by bparees** [comment]
I guess i'll also add that this change seems to violate the principal of "earliest possible return":
https://www.linkedin.com/pulse/early-return-dip-ghosh/

but again, that's to some degree a personal preference, certainly not a hard+fast rule.

**Comment by bparees** [comment]
@tisnik do you want to make a case for this or can we close it?

**Comment by tisnik** [comment]
We can close it, won't be relevant anymore.

**Pull request closed without merging**
