### PR TITLE
OLS-58: Helper method to compute message length

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Helper method to compute message length

## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #[OLS-58](https://issues.redhat.com//browse/OLS-58)

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by raptorsun** [comment]
Is this function equivalent to langchain core's   `get_num_tokens_from_messages` ?
https://github.com/langchain-ai/langchain/blob/8113d612bbc926382ecc8f1907f92d2224c3f063/libs/core/langchain_core/language_models/base.py#L285

**Comment by tisnik** [comment]
> Is this function equivalent to langchain core's `get_num_tokens_from_messages` ? https://github.com/langchain-ai/langchain/blob/8113d612bbc926382ecc8f1907f92d2224c3f063/libs/core/langchain_core/language_models/base.py#L285

not for tiktoken, it's different encoder used

**Pull request merged**
