### PR TITLE
feedback.py: Don't use f-strings in logger

### PR DESCRIPTION
**Pull request by tisnik**
## Description

`feedback.py`: Don't use f-strings in logger

## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)

### CODE REVIEW

**Comment by onmete** [comment]
/hold

What is wrong with fstrings?

**Comment by onmete** [comment]
I understand that, but using fstrings is generally more convenient and readable. The performance impact of evaluating fstring when logging is set to a higher level is less than negligible.

It is recommended by the logging, but the community is split on this topic. To me, readability has a better value here.

Either way, we should be consistent in the logging. I see we have both approaches in our code (for different levels). This PR should unify it across the whole codebase and not just small part of it - this is unnecessarily atomic change, especially with our problems/waiting times on CI.

**Comment by tisnik** [comment]
> Either way, we should be consistent in the logging. I see we have both approaches in our code (for different levels). This PR should unify it across the whole codebase and not just small part of it - this is unnecessarily atomic change, especially with our problems/waiting times on CI.

we are fixing it everywhere as time constraints allow us

**Comment by onmete** [comment]
Isn't it like 30 minutes at most to change it everywhere?

**Pull request closed without merging**
