### PR TITLE
OLS-114: REST API call counter

### PR DESCRIPTION
**Pull request by tisnik**
## Description

REST API call counter in metrics

## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #[OLS-114](https://issues.redhat.com//browse/OLS-114)

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- access `/metrics/` endpoint to see new counter there

### CODE REVIEW

**Comment by raptorsun** [comment]
Hello @tisnik , excuse me for being late to the review ^^"  
I have 2 comments: 
1. Shall we [label the metric ](https://prometheus.github.io/client_python/instrumenting/labels/)`rest_api_calls` with the status code (200 ok, 500 internal error, etc. )?  It will be useful when we diagnose operational incidents. 
2. We can follow the[ Prometheus naming convention ](https://prometheus.io/docs/practices/naming/)by naming `rest_api_calls` as `rest_api_calls_total` for it is a counter without unit.

**Comment by tisnik** [comment]
Hi @raptorsun. Yes good comments. I'm on it.

**Pull request merged**
