### PR TITLE
Fix rag index id to align w/ updated versioned index names

### PR DESCRIPTION
**Pull request by bparees**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by bparees** [comment]
@tisnik fixes the index loading issue you saw, ptal

/assign @tisnik 

@ilan-pinto fyi, in case you change the index ids in the future we need to keep these aligned (eventually we probably want to update the OLS code to just read the index ids out of the metadata)

**Review by tisnik — COMMENTED** [review]
looks good

**Pull request merged**
