### PR TITLE
Update pull request template

### PR DESCRIPTION
**Pull request by tisnik**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Other
-
## Description

Update pull request template

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- N/A

### CODE REVIEW

**Comment by onmete** [comment]
I wonder what is "type of change" good for. Just to give a review a hint or is there some changelog build from those?

LGTM.

**Comment by bparees** [comment]
> I wonder what is "type of change" good for. Just to give a review a hint or is there some changelog build from those?

at least right now i suspect this template is overkill for the rate of change we're going to be dealing with and the small set of contributors we'll have.  It would likely be more helpful with a more mature project that had a wider set of contributors bringing different kinds of contributions to the table.

I definitely want to encourage high quality PR descriptions, but i wonder if this current template is encouraging the opposite because rather than people writing up their own description of what the PR does and why, they are just checking boxes and then not providing additional detail about the change their are proposing.

If nothing else we should probably move "Description" to the top as it is the most important thing to get filled in, imho, and have reviewers start pressing on contributors to provide good descriptions.  

On this topic, related tickets (jira tickets) should be linked in the PR title (e.g. "OLS-1234: implementing foo") as that will trigger automation that handles a bunch of things for us including cross-linking into jira.  Also listing them in the PR description is ok, but having them in the title is more useful.


cc @vishnuchalla

**Comment by vishnuchalla** [comment]
> > I wonder what is "type of change" good for. Just to give a review a hint or is there some changelog build from those?
> 
> at least right now i suspect this template is overkill for the rate of change we're going to be dealing with and the small set of contributors we'll have. It would likely be more helpful with a more mature project that had a wider set of contributors bringing different kinds of contributions to the table.
> 
> I definitely want to encourage high quality PR descriptions, but i wonder if this current template is encouraging the opposite because rather than people writing up their own description of what the PR does and why, they are just checking boxes and then not providing additional detail about the change their are proposing.
> 
> If nothing else we should probably move "Description" to the top as it is the most important thing to get filled in, imho, and have reviewers start pressing on contributors to provide good descriptions.
> 
> On this topic, related tickets (jira tickets) should be linked in the PR title (e.g. "OLS-1234: implementing foo") as that will trigger automation that handles a bunch of things for us including cross-linking into jira. Also listing them in the PR description is ok, but having them in the title is more useful.
> 
> cc @vishnuchalla

+1 on this idea of moving description to the top so that contributors don't miss it.

**Pull request merged**
