### PR TITLE
OLS-137: Feedback aggregator

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Feedback aggregator

An example of CSV file with aggregated feedbacks:

```
Cluster ID,User ID,Conversation ID,Question,LLM response,Sentiment,Feedback
00000000-0000-0000-0000-000000000001,c1143120-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000000,testy test,bla,1,
00000000-0000-0000-0000-000000000002,11111111-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000001,testy test,bla,1,that is awesome
00000000-0000-0000-0000-000000000003,22222222-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000002,testy test,bla,2,that is really awesome
00000000-0000-0000-0000-000000000001,c1143120-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000000,testy test,bla,1,
00000000-0000-0000-0000-000000000002,11111111-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000001,testy test,bla,1,that is awesome
00000000-0000-0000-0000-000000000003,22222222-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000002,testy test,bla,2,that is really awesome
```

This is how the CSV looks like in spreadsheet:

Screenshot from 2024-04-19 13-25-46

Also because of number of items might be huge, statistic is printed at the end of processing:

```
----------------------------------------------------------------------------------------------------
Downloaded tarballs:         8
Tarballs not downloaded:     6
Tarballs with incorrect key: 3
Tarballs without feedback:   0
Feedbacks read:              6
Feedback read errors:        0
Feedbacks aggregated:        6
----------------------------------------------------------------------------------------------------
```

## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [x] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #[OLS-137](https://issues.redhat.com//browse/OLS-137)
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by bparees** [comment]
@tisnik can you give us an example of the output this generates?  (the "report")?

**Comment by tisnik** [comment]
> @tisnik can you give us an example of the output this generates? (the "report")?

Sure, it is taken from feedbacks we already have in the bucket (test feedbacks, of course):

```
User ID,Conversation ID,Question,LLM response,Sentiment,Feedback
c1143120-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000000,testy test,bla,1,
11111111-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000001,testy test,bla,1,that is awesome
22222222-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000002,testy test,bla,2,that is really awesome
```

**Comment by bparees** [comment]
do we have clusterid info available?

**Comment by tisnik** [comment]
> do we have clusterid info available?

yes, is is part of path to object in Ceph:

```
Contents of bucket 'QA-OLS-ARCHIVES':
archives/compressed/5b/5b96fffa-9da9-41ae-9994-a6616aab8d34/202404/08/073607.tar.gz
archives/compressed/71/71993a2b-a5fd-452a-b591-73c7c28c1858/202404/11/153617.tar.gz
archives/compressed/98/98e88e5c-917f-4eec-9279-aac3c730c984/202404/18/110842.tar.gz
archives/compressed/e0/e01b2944-7829-4b82-8e32-c8903a55f048/202404/10/131622.tar.gz
archives/compressed/e5/e55f5cf1-367a-44e3-b95e-1816476c353f/202404/08/094419.tar.gz
archives/compressed/eb/ebccba00-7c78-41f5-a9eb-66b2dfbed564/202404/08/124111.tar.gz
archives/compressed/eb/ebccba00-7c78-41f5-a9eb-66b2dfbed564/202404/08/131312.tar.gz
```

**Comment by bparees** [comment]
seems worth including

**Comment by tisnik** [comment]
> seems worth including

@bparees not it is included as can be seen in description (and on today's demo too)

**Pull request merged**
