### PR TITLE
OLS-83: Use imperative mood in mock classes: according PEP 257

### PR DESCRIPTION
**Pull request by tisnik**
## Description

[OLS-83](https://issues.redhat.com//browse/OLS-83): Use imperative mood in mock classes: according PEP 257
This will allow us to enable the last missing docstyle check: D401

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [x] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- N/A

### CODE REVIEW

**Comment by onmete** [comment]
[Google style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) allows both descriptive/imperative (not at the same time obviously). I'm more used to descriptive, but I have no problem with using imperative.
Can you just make a note to CONTRIBUTING.md about that?

**Comment by tisnik** [comment]
> [Google style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods) allows both descriptive/imperative (not at the same time obviously). I'm more used to descriptive, but I have no problem with using imperative. Can you just make a note to CONTRIBUTING.md about that?

It will be checked on CI and during `make verify` soon. But 1st is to have the sources fixed, with the same style.

**Comment by onmete** [comment]
I didn't know linter could ensure the style. Let's do imperative then.

/lgtm

**Pull request merged**
