### PR TITLE
OLS-40: Llm loader parent error

### PR DESCRIPTION
**Pull request by onmete**
## Description

Contains two commits:
- Custom errors class naming is formatted according to google's standards.
- Adds parent configuration error to make catching these errors easy on the endpoint side (except just parent instead of 5 different ones.)
  - the assumption here is that all those errors are the same from the user's perspective -> 422 unprocessable entity

## Type of change

- [X] Refactor
- [X] New feature

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] PR has passed all pre-merge test jobs.
- [X] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by tisnik** [comment]
/lgtm

(not sure about class hierarchy test, but it can't do any harm anyway)

**Comment by onmete** [comment]
As the intention is to catch the parent error instead of all children, I think it is important to ensure those are actually children. But yeah, it might be an overkill.

**Comment by raptorsun** [comment]
/lgtm
It should be a good idea to have this parent exception. Most times we just need to distinguish configuration error from other errors, no need to dig into the details.

**Pull request merged**
