### PR TITLE
OLS-311: Ability to start service from Python script

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Ability to start service from Python script

## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #[OLS-311](https://issues.redhat.com//browse/OLS-311)

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Simply start the new script: `python runner.py`

### CODE REVIEW

**Comment by onmete** [comment]
You can also use the VSCode launcher for FastAPI. It looks like this
```
{
    "name": "Python: FastAPI",
    "type": "python",
    "request": "launch",
    "module": "uvicorn",
    "args": [
        "ols.app.main:app",
        "--reload",
        "--port",
        "8080"
    ],
    "jinja": true,
    "justMyCode": true
}
```

Can we consider this as a dev feature and maybe just add it to contrib docs and gitignore? Instead of having dev related code in root?

**Comment by bparees** [comment]
> Can we consider this as a dev feature and maybe just add it to contrib docs and gitignore? Instead of having dev related code in root?

@onmete  this isn't dev related code, we're going to pivot to launching OLS this way.  Do you have concerns about that?

The primary motivation is so that we have a proper place to put our env var initialization for env vars we need to set before OLS starts up.  I believe @syedriko had some items to be put there (see https://issues.redhat.com/browse/OLS-345)

@tisnik the code looks fine but are you intending to update our scripts/makefiles/docs to reference this approach?

**Comment by onmete** [comment]
> we're going to pivot to launching OLS this way

no objections than

/lgtm

**Comment by tisnik** [comment]
> @tisnik the code looks fine but are you intending to update our scripts/makefiles/docs to reference this approach?

Yup, I just wanted to know if it's the right direction. I'll continue working on it knowing it's ok-ish :)

**Comment by tisnik** [comment]
@bparees updated Makefile + doc (e2e test script use `make run` already)

**Pull request merged**
