### PR TITLE
Use snake_case consistently in ols config yaml

### PR DESCRIPTION
**Pull request by bparees**
## Description

also cleans up a few error messages

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [x] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by bparees** [comment]
/hold

cannot merge until after https://github.com/openshift/lightspeed-service/pull/278

**Comment by bparees** [comment]
/assign @syedriko 

@syedriko assigning this one to you also since it is a follow-on to https://github.com/openshift/lightspeed-service/pull/278

**Comment by syedriko** [comment]
@bparees I think this needs rebasing to the tip of main to pick up https://github.com/openshift/lightspeed-service/pull/278

**Comment by syedriko** [comment]
... and squashing?

**Review by tisnik — COMMENTED** [review]
it looks ok!

**Pull request merged**
