### PR TITLE
Add olsconfig sample for local ollama server

### PR DESCRIPTION
**Pull request by TamiTakamiya**
## Description

Add olsconfig sample for local ollama server

## Type of change

- [ ] Refactor
- [X] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)

## Related Tickets & Documents

- Related Issue # n/a
- Closes # n/a

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change. n/a
- How were the fix/results from this change verified? Please provide relevant screenshots or results. n/a

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
it looks interesting! Thank you.

**Comment by tisnik** [comment]
/lgtm
/approve
/override "Red Hat Konflux / lightspeed-service-on-pull-request"

**Comment by TamiTakamiya** [comment]
Thank you!

**Pull request merged**
