### PR TITLE
Check auth. mechanism in e2e tests

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Check auth. mechanism in e2e tests

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [x] e2e tests

### CODE REVIEW

**Comment by tisnik** [comment]
/assign @bparees 

Well I'm not sure if it's a good approach. I'd like to have the ability to check auth. mechanism, but the fact, that the test is based on token existence is hacky. OTOH it works in all our CI environments (including OLS with auth. enabled)...

**Comment by bparees** [comment]
seems like a reasonable first pass to me
/label tide-merge-method/squash
/approve
/lgtm

**Pull request merged**
