### PR TITLE
URL validation in config, .coverage cleanup

### PR DESCRIPTION
**Pull request by syedriko**
## Description

- In config model, corrected error handling in the URL validation function
- Made config helpers internal to the config module
- Removed inadvertently committed .coverage.MacBook-Pro.87247.XxFhHddx
- Corrected .gitignore to ignore .coverage*

## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by syedriko** [comment]
@tisnik PTAL

**Comment by tisnik** [comment]
> Removed inadvertently committed .coverage.MacBook-Pro.87247.XxFhHddx

Ah Apple again ;)

**Review by tisnik — COMMENTED** [review]
it looks good!

**Pull request merged**
