### PR TITLE
OLS-657: Bump-up ibm-generative-ai

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Bump-up ibm-generative-ai

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [x] Bump-up dependent library
- [x] Bump-up library or tool used for development (does not change the final image)

## Related Tickets & Documents

- Related Issue #[OLS-657](https://issues.redhat.com//browse/OLS-657)
- Closes #

### CODE REVIEW

**Comment by bparees** [comment]
/approve
/lgtm

```
Starting snyk code scan
Snyk Code is not supported for org openshift-ci-internal: enable in Settings > Snyk Code
Full vulnerabilities report is available at /logs/artifacts/snyk.sarif.json
snyk code scan failed
```

if it doesn't pass on the retest we'll have to talk to DPTP about what's going on.

**Comment by tisnik** [comment]
> /approve /lgtm
> 
> ```
> Starting snyk code scan
> Snyk Code is not supported for org openshift-ci-internal: enable in Settings > Snyk Code
> Full vulnerabilities report is available at /logs/artifacts/snyk.sarif.json
> snyk code scan failed
> ```
> 
> if it doesn't pass on the retest we'll have to talk to DPTP about what's going on.

it was just hiccup, interesting one (@JoaoFula are you interested in those random failures?)

**Comment by bparees** [comment]
> it was just hiccup, interesting one (@JoaoFula are you interested in those random failures?)

since it doesn't seem like something that's OLS specific, i don't think we should worry about it.  If it starts failing consistently we'll need to talk to DPTP about it, but there's nothing to be done from the OLS perspective.

**Pull request merged**
