### PR TITLE
Type safer working with list of messages

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Type safer working with list of messages

## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

### CODE REVIEW

**Comment by onmete** [comment]
I would be fine with just `list[dict]`, this seems too complicated. Do you see value in having such extensive typing information?

**Comment by tisnik** [comment]
> I would be fine with just `list[dict]`, this seems too complicated. Do you see value in having such extensive typing information?

yes, especially with groving code base + ability of IDEs and pilots to detect issues

**Comment by onmete** [comment]
ok

/lgtm

**Pull request merged**
