### PR TITLE
Placeholder instead of unused variable

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Placeholder instead of unused variable

## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)

### CODE REVIEW

**Comment by tisnik** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-service"

**Review by raptorsun — APPROVED** [review]
/lgtm

**Comment by tisnik** [comment]
/override "ci/prow/e2e-ols-cluster-4-15"
/override "ci/prow/e2e-ols-cluster-4-16"
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-service"

**Comment by tisnik** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-service"

**Pull request merged**
