### PR TITLE
Helper commands

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Helper commands:
`pdm run`
`pdm test-unit`

etc.

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Configuration Update
- [ ] Bump-up dependent library

### CODE REVIEW

**Comment by onmete** [comment]
Cool!
Maybe mention the usage in contributing docs?

**Comment by tisnik** [comment]
> Cool! The `pdm run` overides the `pdm run`. Is that good?

updated, just to be sure

**Comment by onmete** [comment]
Maybe also `pdm test` to have the "complete set"?

**Comment by tisnik** [comment]
> Maybe also `pdm test` to have the "complete set"?

good idea! lemme add it

**Comment by bparees** [comment]
bot seems unreliable lately

/lgtm

**Pull request merged**
