### PR TITLE
No global skips for Bandit security checks

### PR DESCRIPTION
**Pull request by tisnik**
## Description

- No global skips for Bandit security checks
- Explicit skips in the code on few places only

## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)

### CODE REVIEW

**Comment by onmete** [comment]
Or maybe disable the rule? It won't prevent pushing the commit with a secret.
It would just fail in CI. If we remove the rule, we move the responsibility to spot a secret to the reviewer.

**Comment by tisnik** [comment]
> Or maybe disable the rule? It won't prevent pushing the commit with a secret. It would just fail in CI. If we remove the rule, we move the responsibility to spot a secret to the reviewer.

the rule is useful to catch these situation. We just have some "artifical" secrets in the code (ideally it won't be the case)

**Pull request merged**
