### PR TITLE
Bump-up llama-index

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Bump-up llama-index

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [x] Bump-up dependent library

### CODE REVIEW

**Comment by tisnik** [comment]
> @tisnik This requires additional changes.. Please refer [OLS-529](https://issues.redhat.com/browse/OLS-529)

yup, I'm just checking there what's going on

**Comment by syedriko** [comment]
@tisnik we probably want to close this in favor of https://github.com/openshift/lightspeed-service/pull/830

**Comment by tisnik** [comment]
> @tisnik we probably want to close this in favor of #830

yup, this one was just a check what happens :)

**Pull request closed without merging**
