### PR TITLE
TLSConfig loading unit tests

### PR DESCRIPTION
**Pull request by tisnik**
## Description

`TLSConfig` loading unit tests

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)
- [x] Unit tests

### CODE REVIEW

**Comment by onmete** [comment]
Since you are touching this, don't you want to refactor the actual config object to pydantic?

**Comment by tisnik** [comment]
> Since you are touching this, don't you want to refactor the actual config object to pydantic?

I'll do later, in separate PR. But yes, that part of sources needs some love ;)

**Pull request merged**
