### PR TITLE
Update contrib install instructions

### PR DESCRIPTION
**Pull request by onmete**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [X] Documentation Update

## Description

Updated contributing documentation and pre-commit dependencies.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Review by tisnik — APPROVED** [review]
LGTM

**Review by thoraxe — CHANGES_REQUESTED** [review]
As this is a markdown file, things with `#` are header sections. I'm not sure why you would uncapitalize titles (Clone -> clone).

I can see un-capitalizing "virtual environment" but "Python" is a proper noun.

But, in spite of all that, as these are section headings, I wonder if they shouldn't appropriately be title case and not sentence case:
https://titlecaseconverter.com/blog/sentence-case-vs-title-case/

But "no capitals-case" is probably not what we want here.

@bparees WDYT?

**Comment by onmete** [comment]
@thoraxe Those are inline code comments, not markdown titles.

**Comment by bparees** [comment]
/ok-to-test
/lgtm
/approve

> But "no capitals-case" is probably not what we want here.

since they are just incline script comments, all lower case is fine.    As it was would have been fine too imho, so i hope not to see too much of people making personal preference style edits(we need to focus on more material concerns), but since this PR also updates some steps that were legitimately wrong/out of date, i'm ok with it in this case.

@onmete if you join the openshift github org, we will no longer have to explicilt approve testing for your PRs

**Pull request merged**
