### PR TITLE
Change to `registry.redhat.io`

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Change to `registry.redhat.io`

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)

### CODE REVIEW

**Comment by tisnik** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-service"

**Comment by raptorsun** [comment]
After testing in local cluster, it seems we need setup a imagedigestmirrorset to make it work. the current bundle image reference is not available at registry.redhat.io but in quay.io. I will make a fix PR shortly

**Comment by raptorsun** [comment]
fix for E2E test https://github.com/openshift/lightspeed-service/pull/1659

**Pull request merged**
