### PR TITLE
Fix junit setup template variable name reference

### PR DESCRIPTION
**Pull request by bparees**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by bparees** [comment]
not sure how long this was broken, i guess we haven't been hitting many OLS startup timeouts lately.

/assign @xrajesh

**Review by tisnik — COMMENTED** [review]
looks ok

**Comment by bparees** [comment]
/hold

gonna do a little test on this and then i'll merge it.

**Pull request merged**
