### PR TITLE
OLS-497: minimize image rebuilds by leveraging layer caching

### PR DESCRIPTION
**Pull request by vbelouso**
## Description

Allows to avoid unnecessary container rebuilding when changing the OLS code

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [x] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes https://issues.redhat.com/browse/OLS-497

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
is the goal to have "ols" as the last layer because it is updated too frequently? I mean, there are no other changes there AFAIK

**Comment by vbelouso** [comment]
> is the goal to have "ols" as the last layer because it is updated too frequently? I mean, there are no other changes there AFAIK

The goal is to do a quick rebuild (using the cache) after the source code in `ols` has been changed.
Moreover it's [best practice](https://docs.docker.com/build/cache/#order-your-layers) to install dependencies first and then copy the code

**Review by tisnik — COMMENTED** [review]
yup, looks good and thank you

**Pull request merged**
