### PR TITLE
Delete the /debug/query endpoint

### PR DESCRIPTION
**Pull request by bparees**
this endpoint doesn't have auth protections and isn't something we want to make available to our users, at this point I have it has served its purpose

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by bparees** [comment]
/assign @asamal4 

@asamal4 @williamcaban @ilan-pinto you are the 3 most likely making use of this endpoint, if anyone is (to have a way to submit raw queries to llms to test various prompts w/o the default ols system prompts getting in the way), so if it's important to you let's talk about how to replace that functionality before merging this.

otherwise, please lgtm it if you're ok with it.

**Comment by williamcaban** [comment]
Same here. I use out-of-band direct access for external providers and OLS general API endpoint for OLS-specific results.

**Comment by bparees** [comment]
> generate_bare_response function definition (used only for debug endpoint) also can be removed.

thanks, i've removed that also

> Note: Not related to this PR directly.. As we are talking about debug, perhaps we can discuss later about how can we debug/test with cluster context & iterate quickly on complete prompt. Or this is something that we will copy from console and test in local gradio UI ?

yeah if you're looking to quickly iterate i'd suggest using the gradio ui with a local OLS instance.

**Pull request merged**
