### PR TITLE
OLS-581: Move the program logic to wait for OLS

### PR DESCRIPTION
**Pull request by Nehanth**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
it's like 5th iteration, the previous "OLS-581" PRs were closed w/o merge. Is it because of rebase that did not work for any reason?

**Comment by Nehanth** [comment]
> it's like 5th iteration, the previous "OLS-581" PRs were closed w/o merge. Is it because of rebase that did not work for any reason?

yes

**Pull request merged**
