### PR TITLE
Bump-up Prometheus client

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Bump-up Prometheus client

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [x] Bump-up dependent library

### CODE REVIEW

**Comment by bparees** [comment]
you want to wait and use this as a test case for dependabot?  or is there an urgency to get this bumped?

/approve

**Comment by tisnik** [comment]
> you want to wait and use this as a test case for dependabot? or is there an urgency to get this bumped?
> 
> /approve

This issue https://github.com/prometheus/client_python/pull/999 occurs time to time on my machine, so it might occur on clutsers too. IMHO better to update.

**Pull request merged**
