### PR TITLE
Refactor: simpler return statement, not need to use intermediate vari…

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Refactor: simpler `return` statement, not need to use intermediate variable

## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

### CODE REVIEW

**Comment by onmete** [comment]
I'm doing that on purpose. With that, I can set the debug point on return and see what it is returning. With this, I would set the point on return and need to evaluate the statement in the debugger.

But I don't have any argument besides that. 🤷‍♂️

**Comment by tisnik** [comment]
> I'm doing that on purpose. With that, I can set the debug point on return and see what it is returning. With this, I would set the point on return and need to evaluate the statement in the debugger.
> 
> But I don't have any argument besides that. 🤷‍♂️

if you put breakpoint at return statement, you will see the computed return value too

**Comment by tisnik** [comment]
> where? image

fff

**Comment by onmete** [comment]
Well, yea, but you need to be one level above.

As I said, it's my personal thing. I'll try to remember it from now on.

/lgtm

**Pull request merged**
