### PR TITLE
Refactor: QueryHelper class in it's own file

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Refactor: `QueryHelper` class in it's own file.
It's quite uncommon to have class definition and the logic around (logging) directly in `__init__.py`
Also the primary use of `__init__.py` is to initialize Python packages and not to hold content.

## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm
/approve

thanks, i was wondering about this

**Comment by tisnik** [comment]
(had to rebase as tests have changed in between)

**Pull request merged**
