### PR TITLE
Use plain old teste function instead of methods where appropriate

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Use plain old teste function instead of methods where appropriate

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [x] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by onmete** [comment]
I see you don't like the classes there. :)

Could you just remove the class and have the methods as plain test functions instead?

**Comment by tisnik** [comment]
> I see you don't like the classes there. :)
> 
> Could you just remove the class and have the methods as plain test functions instead?

Well both are correct. But ATM when there are no shared state, it does not make much sense to use instance methods, because static methods are ok/sufficient/more optional.

**Comment by tisnik** [comment]
> @tisnik i'm pretty sure i've seen people creating PRs going the other way (wrapping test functions into test classes) too, so let's make sure we're not fighting each other on these patterns.

So should we update contributing guide?

**Comment by bparees** [comment]
> So should we update contributing guide?

i don't know if it will help :)  for now i'll settle for having raised awareness.  sorry, wish i could point to the other PR i am thinking of.

**Pull request merged**
