### PR TITLE
OLS-703: Script to print EC failures

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Script to print EC failures

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)
- [x] Tools

## Related Tickets & Documents

- Related Issue #[OLS-703](https://issues.redhat.com//browse/OLS-703)

### CODE REVIEW

**Comment by tisnik** [comment]
/override "Red Hat Konflux / lightspeed-service-on-pull-request"

**Review by raptorsun — APPROVED** [review]
/lgtm

**Pull request merged**
