### PR TITLE
OLS-302: Unit tests: Redis retry settings on Redis client initialization

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Unit tests: Redis retry settings on Redis client initialization

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [x] Unit tests

## Related Tickets & Documents

- Related Issue #[OLS-302](https://issues.redhat.com//browse/OLS-302)

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Use `make test-unit`

### CODE REVIEW

**Review by onmete — COMMENTED** [review]
When `retry_on_error` and `retry_on_timeout` set to `True`/`"true"`, it should be `True`, but every other value ends up as `False` (according to how it is defined in config), right?

So why are there checks against `None`?

**Comment by tisnik** [comment]
> When `retry_on_error` and `retry_on_timeout` set to `True`/`"true"`, it should be `True`, but every other value ends up as `False` (according to how it is defined in config), right?
> 
> So why are there checks against `None`?

retry_on_error is not bool in the end. It's list of exception classes

**Pull request merged**
