### PR TITLE
Added missing unit tests for readiness endpoint

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Added missing unit tests for readiness endpoint

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)
- [x] Unit tests

### CODE REVIEW

**Comment by onmete** [comment]
I think this is tested in integration tests.

**Comment by tisnik** [comment]
> I think this is tested in integration tests.

I hope so (indirectly via running client, right)? What does it mean?

**Pull request merged**
