### PR TITLE
Consistent Pytest fixture usage in tests

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Consistent Pytest fixture usage in tests

Either removing unnecessary parentheses _or_ requiring them for all
fixtures is fine, but it's best to be consistent. It is better to
removing unnecessary parentheses, to match the documentation of the
official `pytest` projects.

## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)
- [ ] CI configuration change
- [ ] Konflux configuration change

### CODE REVIEW

**Comment by onmete** [comment]
It was not that long when we were adding parentheses everywhere.

**Comment by tisnik** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-service"

**Pull request merged**
