### PR TITLE
OLS-47: Add pdm as dependency managent tool

### PR DESCRIPTION
**Pull request by onmete**
## Type of change

- [ ] Refactor
- [X] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Description

Adds pdm as a dependency management tool.

## Related Tickets & Documents

[OLS-47](https://issues.redhat.com/browse/OLS-47)

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
That would be very nice to switch to PDM

**Comment by bparees** [comment]
Makefile targets need to be updated (make install-deps, make install-deps-test), right?

**Comment by onmete** [comment]
> Makefile targets need to be updated (make install-deps, make install-deps-test), right?

Yes. I also updated a few other places accordingly (docs, dependabot, ...) and added `pydantic==2.6.0` from the other PR.

**Comment by onmete** [comment]
CI update - https://github.com/openshift/release/pull/48195
It should work, but I don't know how I can test it before merging.

**Comment by bparees** [comment]
/lgtm
/approve

/hold

needs https://github.com/openshift/release/pull/48195 to merge first, hopefully that fixes the broken unit+integration tests.

I also want to see this pass the `e2e-ols-openai-gpt35` test before we merge it though

**Pull request merged**
