### PR TITLE
eval: fix errors while data concatenation

### PR DESCRIPTION
**Pull request by asamal4**
## Description

Fix errors during data concatenation. (Missed to push local changes earlier)

### CODE REVIEW

**Comment by tisnik** [comment]
/lgtm
/approve
/override "ci/prow/verify"
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-service"

**Comment by xrajesh** [comment]
/override "Red Hat Konflux / lightspeed-service-on-pull-request"

**Pull request merged**
