### PR TITLE
Use provider type, not provider name, as metrics label

### PR DESCRIPTION
**Pull request by bparees**
## Description

provider name can be whatever the admin wants.  provider type has to be one of our explicit known values.  For purposes of us understanding which providers customers are using, we want the type(azure_openai, openai, watsonx, etc), not their arbitrary name for the provider config.

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by bparees** [comment]
@tisnik ptal

does not break existing tests because all our existing configs use the same value for `name` and `type`.  Which is probably something to fix in the future to make sure we are always using the right field in the right spots.  When both values are the same it masks cases where we are using the wrong value.

**Review by tisnik — COMMENTED** [review]
yes, that's indeed better

**Pull request merged**
