### PR TITLE
Invoke pdm sync to make sure packages are installed according to pmd.lock

### PR DESCRIPTION
**Pull request by syedriko**
## Description

Invoke pdm sync to make sure packages are installed according to pmd.lock
 Added a separate target for "pdm install" for picking up pyproject.toml updates.

## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by bparees** [comment]
needs to introduce a new make target for when we actually want to update the lock file with new deps

**Review by tisnik — COMMENTED** [review]
it looks ok

prob checking deps first might be added too

**Pull request merged**
