### PR TITLE
Script to list objects stored in Ceph bucket

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Script to list objects stored in Ceph bucket
(will be also used as an example in our internal documentation)

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [x] Utility

### CODE REVIEW

**Review by onmete — COMMENTED** [review]
Is this something that should be part of this repo? I mean there is a lot of clutter and stuff that doesn't necessary belong here anyway. So when we do a cleanup, this should be moved elsewhere (docs) too right?

**Comment by tisnik** [comment]
> Is this something that should be part of this repo? I mean there is a lot of clutter and stuff that doesn't necessary belong here anyway. So when we do a cleanup, this should be moved elsewhere (docs) too right?

I had exactly the same question about sidecar and other scripts.

**Comment by onmete** [comment]
So the answer is: _it is fiiine for now_ 😅 

/lgtm

**Comment by bparees** [comment]
> I had exactly the same question about sidecar and other scripts.

the sidecar is logic is literally part of the core OLS application + image, so this isn't the same as that.

That said, i don't see a reason to go off and create another repo for this.  But i do think the directory structure could use some work.  The "scripts" dir contains quite a variety of unrelated bits at this point, i'd like to see some better directory/subdirectory name+structure so it's not just a dumping ground of random dev/tool/reporting/testing scripts.

**Pull request merged**
