### PR TITLE
OLS 0.2.0 version update

### PR DESCRIPTION
**Pull request by syedriko**
## Description

OLS 0.2.0 version update

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)
- [ ] CI configuration change
- [ ] Konflux configuration change

## Related Tickets & Documents

- Related Issue # https://issues.redhat.com/browse/OLS-1083
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Review by tisnik — CHANGES_REQUESTED** [review]
you need to change projectfile too

**Comment by tisnik** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-service"

**Comment by xrajesh** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-service"
/override "Red Hat Konflux / ols-enterprise-contract / pr group syedriko-ols-release-0.2.0"

**Comment by tisnik** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / pr group syedriko-ols-release-0.2.0"

**Pull request merged**
