### PR TITLE
OLS-302: Atomic writing into Redis based on optimistic locking

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Atomic writing into Redis based on optimistic locking algorithm
Tested against real Redis instance

## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #[OLS-302](https://issues.redhat.com//browse/OLS-302)
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] PR has passed all pre-merge test jobs.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
code wise looks good. But how did you test and verify its working against a real redis instance? Can you share more details for understanding please?

**Comment by tisnik** [comment]
> code wise looks good. But how did you test and verify its working against a real redis instance? Can you share more details for understanding please?

Yes sure. It was tested by long running 2 running clients - one real one (our

**Comment by tisnik** [comment]
> code wise looks good. But how did you test and verify its working against a real redis instance? Can you share more details for understanding please?

Yes it was tested against real Redis by using two data producers, each one appending different sequence of messages. Yesterday we agree not to invest time into this sort of integration tests, so it is not complete (to be reviewed as PR), but the test looks like: https://gist.github.com/tisnik/4a812d019441399e6f7db26066c14838

**Comment by vishnuchalla** [comment]
> > code wise looks good. But how did you test and verify its working against a real redis instance? Can you share more details for understanding please?
> 
> Yes it was tested against real Redis by using two data producers, each one appending different sequence of messages. Yesterday we agree not to invest time into this sort of integration tests, so it is not complete (to be reviewed as PR), but the test looks like: https://gist.github.com/tisnik/4a812d019441399e6f7db26066c14838

Thanks for clarifying.

**Comment by bparees** [comment]
/close

obsolete due to pivot away from redis

**Pull request closed without merging**
