### PR TITLE
Log where we loaded the config file from

### PR DESCRIPTION
**Pull request by bparees**
## Description

$ make run
uvicorn ols.app.main:app --reload --port 8080
INFO:     Will watch for changes in these directories: ['/home/bparees/git/gocode/src/github.com/openshift/lightspeed-service']
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [1009276] using StatReload
2024-01-31 14:48:40,144 [ols.app.main:main.py:24] INFO: Config loaded from olsconfig.yaml
2024-01-31 14:48:40,144 [ols.app.main:main.py:30] INFO: Embedded Gradio UI is disabled. To enable set enable_dev_ui: true in the dev section of the configuration file
INFO:     Started server process [1009278]
INFO:     Waiting for application startup.
INFO:     Application startup complete.

## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] PR has passed all pre-merge test jobs.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by bparees** [comment]
@thoraxe we already throw an exception if the config.yaml can't be loaded/found:


```
$ make run
uvicorn ols.app.main:app --reload --port 8080
INFO:     Will watch for changes in these directories: ['/home/bparees/git/gocode/src/github.com/openshift/lightspeed-service']
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [1009677] using StatReload
Failed to load config file olsconfig.yaml: expected a single document in the stream
  in "olsconfig.yaml", line 1, column 1
but found another document
  in "olsconfig.yaml", line 2, column 1
```

```
$ make run
uvicorn ols.app.main:app --reload --port 8080
INFO:     Will watch for changes in these directories: ['/home/bparees/git/gocode/src/github.com/openshift/lightspeed-service']
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [1009791] using StatReload
Failed to load config file olsconfig.yaml: [Errno 2] No such file or directory: 'olsconfig.yaml'
```

**Review by tisnik — COMMENTED** [review]
looks ok
(prob we might also print the full path on line 20, just in case)

**Comment by bparees** [comment]
/hold cancel

@tisnik updated to print full path

```
$ make run
uvicorn ols.app.main:app --reload --port 8080
INFO:     Will watch for changes in these directories: ['/home/bparees/git/gocode/src/github.com/openshift/lightspeed-service']
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [1010803] using StatReload
2024-01-31 15:04:45,631 [ols.app.main:main.py:25] INFO: Config loaded from /home/bparees/git/gocode/src/github.com/openshift/lightspeed-service/olsconfig.yaml
```

**Review by tisnik — COMMENTED** [review]
full path is even better to have on terminal

**Pull request merged**
