### PR TITLE
Bump-up ibm-watsonx-ai to 1.1.8

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Bump-up `ibm-watsonx-ai` to 1.1.8

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [x] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)

### CODE REVIEW

**Comment by raptorsun** [comment]
/lgtm
[ecosystem-cert-preflight-checks](https://console.redhat.com/preview/application-pipeline/ns/crt-nshift-lightspeed-tenant/pipelinerun/lightspeed-service-on-pull-request-cl6td/logs/ecosystem-cert-preflight-checks) failed but does not seem related to this particular change.

**Comment by tisnik** [comment]
/override "Red Hat Konflux / lightspeed-service-on-pull-request"

**Pull request merged**
