### PR TITLE
Proper names for fixtures not returning values

### PR DESCRIPTION
**Pull request by tisnik**
## Description

By convention, fixtures that don't return a value should be named with a
leading underscore, while fixtures that do return a value should not.

## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library

### CODE REVIEW

**Comment by onmete** [comment]
¯\\\_(ツ)\_/¯

It makes sense to some extent, but I'm a bit afraid the number of various rules and conventions is getting out of hand.
I certainly wouldn't be able to remember them all. So it would be up to you to keep it in mind in reviews.

/lgtm

**Comment by bparees** [comment]
> It makes sense to some extent, but I'm a bit afraid the number of various rules and conventions is getting out of hand.
I certainly wouldn't be able to remember them all. So it would be up to you to keep it in mind in reviews.

+1, also seems to provide marginal value.  What benefit does one gain from this knowledge being encoded in the naming convention?  I generally don't call a function w/o looking at its definition to know what args it takes and what it returns, at a minimum.

**Comment by bparees** [comment]
doesn't touch e2e tests so we can merge this w/o passing e2e-cluster

**Pull request merged**
