### PR TITLE
OLS-233: Use Optional type instead of | operator

### PR DESCRIPTION
**Pull request by onmete**
## Description

Seems we are using `Optional` instead of `something | None`. 

## Type of change

- [X] Refactor

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
looks ok

**Comment by bparees** [comment]
i had been pushing for the use of `|` syntax in PRs i reviewed because my understanding is that it is the newer/more modern syntax.

https://peps.python.org/pep-0655/ states:

```
Optional[] is too ubiquitous to deprecate, although use of it may fade over time in favor of the T|None notation specified by [PEP 604](https://peps.python.org/pep-0604/).
```

**Pull request merged**
