### PR TITLE
Info about LLMS providers and registry

### PR DESCRIPTION
**Pull request by tisnik**
## Description

Info about LLMS providers and registry

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CVE fix
- [ ] Optimization
- [x] Documentation Update
- [ ] Configuration Update
- [ ] Bump-up dependent library
- [ ] Bump-up library or tool used for development (does not change the final image)

### CODE REVIEW

**Comment by onmete** [comment]
It is in contributing too - https://github.com/openshift/lightspeed-service/blob/main/CONTRIBUTING.md#adding-a-new-providermodel
I would prefer only one place for this information (I don't care where).
WDYT?

**Comment by tisnik** [comment]
/override "Red Hat Konflux / ols-e2e-tests-rosa / lightspeed-service"

**Comment by tisnik** [comment]
/override "Red Hat Konflux / ols-enterprise-contract / lightspeed-service"

**Pull request merged**
